language: csharp
solution: ./src/ToDo.Web.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
- dotnet restore ./src/ToDo.Web
- dotnet build ./src/ToDo.Web/
- dotnet test ./src/Todo.Web.Tests/
branches:
  only:
  - master
deploy:
  provider: azure_web_apps
  username: "$AZURE_WA_USERNAME"
  password: "$AZURE_WA_PASSWORD"
  site: "$AZURE_WA_SITE"
  verbose: true
